## Listar todos os pacientes
GET https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/pacientes

### Buscar paciente por ID
GET https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/pacientes/1

### Criar um novo paciente
POST https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/pacientes
Content-Type: application/json

{
    "nome": "Ana Beatriz",
    "email": "ana.beatriz@email.com"
}

### Atualizar um paciente existente (ID 1)
PUT https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/pacientes/1
Content-Type: application/json

{
    "nome": "Ana Beatriz Souza",
    "email": "ana.souza@email.com"
}

### Deletar um paciente existente (ID 1)
DELETE https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/pacientes/1

####################################################################################

                    ######      TESTE INFOPRODUTOS   ######

####################################################################################

### Criar um novo Infoproduto
POST https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/infoprodutos
Content-Type: application/json

{
    "nome": "E-book Receitas Fit",
    "descricao": "Um guia completo com 50 receitas saudáveis.",
    "preco": 49.90
}

### buscar infoprodutos na lista
GET https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/infoprodutos

### put para mudar o valor do infoproduto
PUT https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/infoprodutos/1
Content-Type: application/json

{
    "nome": "E-book Receitas Fit",
    "descricao": "Um guia completo com 50 receitas saudáveis",
    "preco": 59.90
}

###############################################################
        ###          TESTES CONSULTAS         ###
#################################################################

### criar uma nova consulta para o paciente com ID 1
POST https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/consultas
Content-Type: application/json 

{
    "dataConsulta": "2025-10-15",
    "anotacoes" :"Primeira consulta de avaliação. Paciente relata baixa energia ao acordar",
    "paciente": {
        "id": 1
    }
}

### metodo para buscar todo o relatório de consulta do cliente
GET  https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/consultas/paciente/1

### metodo para mudar o texto das anotacoes
PUT https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/consultas/1
Content-Type: application/json

{
    "anotacoes": "Paciente relatou melhora de energia",
    "dataConsulta": "2025-10-15"
}

### deletar uma consulta
DELETE https://legendary-broccoli-jjr44rxrgvv425x5v-8080.app.github.dev/consultas/1